baseURL = "https://can.blagorussia.ru/"
languageCode = "ru-ru"
title = "САН - Сообщество агентов недвижимости"

[params]
  description = "САН - Сообщество агентов недвижимости"
  author = "НП «Общественное благополучие Воронежа»"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
