baseURL = "https://can.blagorussia.ru/"
languageCode = "ru-ru"
title = "САН - Сообщество агентов недвижимости"

[params]
  description = "САН, это некоммерческий проект, целью которого является улучшение взаимодействия участников рынка недвижимости на принципах MLS-AREA (Мультилистинговой системы) сотрудничества"
  author = "НП «Общественное благополучие Воронежа»"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
